2021-06-03 15:13:24,091 main.py: [WinError 3] The system cannot find the path specified: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\SEQUENCES'
2021-06-03 16:36:29,814 main.py: [WinError 183] Cannot create a file when that file already exists: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\Images_data/06032021'
2021-06-03 16:47:31,045 main.py: [WinError 183] Cannot create a file when that file already exists: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\Images_data/06032021'
2021-06-03 16:47:55,755 main.py: [WinError 3] The system cannot find the path specified: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\SEQUENCES'
2021-06-03 16:47:55,864 main.py: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2021-06-03 16:59:33,133 main.py: [WinError 183] Cannot create a file when that file already exists: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\Images_data/06032021'
2021-06-03 17:00:15,756 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:00:36,870 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:00:41,463 main.py: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2021-06-03 17:01:03,152 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:01:24,156 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:01:45,935 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:02:06,941 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:02:28,950 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:07:08,232 main.py: [WinError 183] Cannot create a file when that file already exists: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\Images_data/06032021'
2021-06-03 17:07:51,303 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:08:12,310 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:08:16,018 main.py: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2021-06-03 17:08:37,245 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:08:58,249 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:09:19,308 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:09:40,312 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:10:01,453 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:16:12,597 main.py: [WinError 183] Cannot create a file when that file already exists: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\Images_data/06032021'
2021-06-03 17:16:55,683 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:17:08,881 main.py: [WinError 183] Cannot create a file when that file already exists: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\Images_data/06032021'
2021-06-03 17:17:51,432 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:18:12,436 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:18:15,585 main.py: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2021-06-03 17:18:36,829 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:19:55,287 main.py: [WinError 183] Cannot create a file when that file already exists: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\Images_data/06032021'
2021-06-03 17:20:40,825 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:21:01,836 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:21:26,419 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:21:47,430 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:22:08,952 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:22:29,959 main.py: 'NoneType' object has no attribute 'execute'
2021-06-03 17:50:13,113 main.py: lines 67 [WinError 183] Cannot create a file when that file already exists: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\Images_data/06032021'
2021-06-03 18:02:18,887 main.py: lines 67 [WinError 183] Cannot create a file when that file already exists: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\Images_data/06032021'
2021-06-03 18:03:04,292 main.py: lines 530'NoneType' object has no attribute 'fetchall'
2021-06-03 18:03:25,303 main.py: lines 544'NoneType' object has no attribute 'fetchall'
2021-06-03 18:03:50,318 main.py: lines 530'NoneType' object has no attribute 'fetchall'
2021-06-03 18:04:11,336 main.py: lines 544'NoneType' object has no attribute 'fetchall'
2021-06-03 18:04:32,442 main.py: lines 530'NoneType' object has no attribute 'fetchall'
2021-06-03 18:04:53,447 main.py: lines 544'NoneType' object has no attribute 'fetchall'
2021-06-03 18:05:15,439 main.py: lines 530'NoneType' object has no attribute 'fetchall'
2021-06-03 18:05:36,445 main.py: lines 544'NoneType' object has no attribute 'fetchall'
2021-06-03 18:05:58,439 main.py: lines 530'NoneType' object has no attribute 'fetchall'
2021-06-03 18:06:19,444 main.py: lines 544'NoneType' object has no attribute 'fetchall'
2021-06-03 18:12:53,368 main.py: lines 67 [WinError 183] Cannot create a file when that file already exists: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\Images_data/06032021'
2021-06-03 18:13:15,037 main.py: lines 67 [WinError 183] Cannot create a file when that file already exists: 'E:\\2022\\Work\\SamSung\\Send_MrTin (1)\\Send_MrTin\\Images_data/06032021'
2021-06-03 18:13:15,131 main.py: lines 479'MainWindow' object has no attribute 'mapping_data'
2021-06-03 18:47:19,186 main.py: lines 530'NoneType' object has no attribute 'execute'
2021-06-03 18:47:40,537 main.py: lines 544'NoneType' object has no attribute 'execute'
2021-06-03 19:14:16,139 main.py: lines 530'NoneType' object has no attribute 'execute'
2021-06-03 19:14:37,143 main.py: lines 544'NoneType' object has no attribute 'execute'
2021-06-03 19:15:01,666 main.py: lines 530'NoneType' object has no attribute 'execute'
